### ISSUE TITLE
Can't edit consumer key for IDIR accounts

### ISSUE THREAD

**Issue by BK01** [bcgov/cpf#10]
CPF admin app: When viewing the properties page for a user account (IDIR) you cannot edit the consumer key or consumer secret. You only see an 'active' checkbox in the edit screen but no textbox listing the key, secret or a 'generate consumer secret' button.

**Comment by pauldaustin** [comment]
This is by design. IDIR accounts you login via the common login page. The consumer key and secret are only supported for CPF accounts for applications to access via the Digest login.

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
