### ISSUE TITLE
Wrong fields are populated on single request jobs

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/cpf#11]
Create single request job
civicNumber=1820
streetName="E KENT"
streetType=AV
streetDirection=S
localityName=vancouver
provinceCode=BC

Submitted as batch job 4737

Get the following message in errorResult file:

interpolation=1820 not in ({adaptive=adaptive, linear=linear, none=none})

**Comment by pauldaustin** [comment]
Each plugin has two record definitions. These were sharing the same field definition object which resulted in the wrong field index being used. These field definitions are no cloned to avoid this issue.

**Comment by mraross** [comment]
verified

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
