### ISSUE TITLE
page is incorrectly scrolled down after returning to batch job tab in batch job page

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#12]
1. Start in batch job info tab for a given job.
2. Select Status Changes tab.
3. Select batch job info tab again. Page will be scrolled down but should still be at the top.

Example:
https://delivery.apps.gov.bc.ca/pub/cpf/secure/ws/jobs/4854/#batchJob_clientView

**Comment by pauldaustin** [comment]
Works in Chrome and Safari. Must be a bug in bootstrap/firefox

**Comment by BK01** [comment]
Validated in CPF 5.1.3. No longer an issue.
