### ISSUE TITLE
batchMode permission setting to hasAnyRole(...) not working

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#13]
in CPF admin,in batch geocoder app config, changing batch mode permission to the following disallows idir accounts from accessing geocoder. This works in prod.

```
hasAnyRole('BCGOV_INTERNAL','BGEO_EXTERNAL','BGEO_EXTERNAL_GOV','BGEO_APPS_GOV','BGEO_APPS_EXTERNAL')
```

**Comment by mraross** [comment]
It might be just BCGOV_INTERNAL that is giving problems because the following instant mode permission does work for the PIG:

```
hasAnyRole('SID2PID_USERS','SID2PID_APPS_GOV')

**Comment by mraross** [comment]
tried the following as per admin guide:
```
hasAnyRole('ROLE_BCGOV_INTERNAL')
```
and it doesn't work either

**Comment by pauldaustin** [comment]
The code to add the BCGOV groups wasn't being initialized properly.

**Comment by mraross** [comment]
Verified in Test
