### ISSUE TITLE
Remove obsolete admin groups for deleted MTWS and GVWS modules

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#14]
Remove the following user groups from CPF initial config:

```
ADMIN_MODULE_MTWS_ADMIN
ADMIN_MODULE_MTWS_SECURITY
ADMIN_MODULE_GVWS_ADMIN
ADMIN_MODULE_GVWS_SECURITY
```

It looks like they got forgotten when module names were changed to GEOMETRY_VALIDATION AND MAPTILE.

**Comment by pauldaustin** [comment]
Code to delete had the keyword ADMIM rather than ADMIN in the query that deleted the user groups for the module.

Fixed that.

Once deployed I'll add a dummy module with those names and then delete the module to clean them up and verify the delete works.

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
