### ISSUE TITLE
CPF version and timestamp not displayed in footer

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#15]
If you scroll the following page to the bottom:

```
https://delivery.apps.gov.bc.ca/pub/cpf/secure/ws/apps/geocoder/
```

the CPF version and timestamp will appear. When not scrolled to the bottom, the version and timestamp are not displayed. Also, all pages that are too short to scroll don't have versions and timestamps in the footer.

**Comment by pauldaustin** [comment]
Modified CSS to fix the location based off the bottom of the page. Also modified it to be left aligned in the case that the screen size is less than 800px

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
