### ISSUE TITLE
Results tab not created in job page

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#16]
When you submit a job and refresh the Status Changes tab in the job info page, the results tab never appears when the status gets changed to resultsCreated. 

https://delivery.apps.gov.bc.ca/pub/cpf/secure/ws/jobs/4896/#batchJob_clientView

**Comment by pauldaustin** [comment]
Cannot verify as the job no longer exists.

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
