### ISSUE TITLE
in submit multiple request job, if you supply both an input file name and an input url, you get an HTTP 400 error

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#27]
If you clear the input file name, the job is submitted successfully. Just change the behavior to one of two alternatives:
1. Display an error message in the form.
2. Ignore the input file name and just use the URL.

**Comment by BK01** [comment]
Verified as resolved. The CPF displays correct error message "The inputData file or inputDataUrl parameter must be specified, but not both"
