### ISSUE TITLE
Job logs are being incorrectly deleted when old jobs are being purged

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#34]
Job logs older than removeOldBatchJobs.daysToKeepOldJobs days are being deleted and shouldn't be. The whole point of these logs is to have a historic record of jobs instead of losing this information every N days. CPF administrators will manually manage old logs.

**Comment by pauldaustin** [comment]
Leo,

Can you exclude the jobs/ sub directory of the cpf app logs from being deleted automatically. Michael want to keep logs of what jobs were completed on specific days and maintain those for reporting purposes.

If that is not possible can you let me know a different path to store them in.

**Comment by pauldaustin** [comment]
Michael, 

This is nothing to do with the removeOldBatchJobs.daysToKeepOldJobs. This is due to the log folder being deleted on restart or by Leo for files older than a date.

**Comment by ll911** [comment]
@pauldaustin access logs should not be stored within container `$CATALINA_BASE/logs` , @mraross just need the summary of the access logs not full details.

**Comment by pauldaustin** [comment]
Leo,

These are not "access logs" in the web sense of access logs.

The file basically shows minimal information about each job when completed so we can analyze the usage patterns of the application.

See the attached file for an example of the file that is created (open as tab separated file in Excel).  

If you let me know what directory it should be created in (e.g. /apps/cpf/reports) and I'll update the config to point to that location.

Somehome that directory should be made available to authorized users (Michael) either via a network share or HTTP access.

**Comment by pauldaustin** [comment]
[jobs-2016-09-06.tsv.zip](https://github.com/bcgov/cpf/files/460351/jobs-2016-09-06.tsv.zip)

**Comment by ll911** [comment]
@pauldaustin such info should be stored in database or filestore(persistent storage), at the moment, `$CATALINA_BASE/*` should not be used for storing such content, as container can be removed completely as it get created during the application deployment.  also there is no filestore(permanent) attached with application server, therefore those metadata should be stored in database

**Comment by mraross** [comment]
Verified
