### ISSUE TITLE
in bgeo plugin, getting default kml styling instead of custom styling as per previous version of CPF

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#35]
bgeo CPF plugin kml style configuration was left same as previous version of CPF. Does it have to change in v5.0 to get custom styles that were coming out in previous version? If not, this may be a bug. See batch job 5756 on delivery

**Comment by pauldaustin** [comment]
Typo in schema for sending results from worker to master resulted in the configuration parameters being lost

**Comment by mraross** [comment]
Verified in test
