### ISSUE TITLE
Link to dashboard missing from the admin menu

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/cpf#37]
The admin menu doesn't include a link to the dashboard page. However manually entering the URL shows the link.

**Comment by pauldaustin** [comment]
Added a link from the admin toolbar.

Also the styling of the table was the old jquery. Updated to use boostrap

**Comment by mraross** [comment]
Verified in revolsys dev environment

**Comment by mraross** [comment]
Verified in prod
