### ISSUE TITLE
In revolsys dev environment, got Ajax error after hitting Jobs tab in CPF client running on Firefox v49.0.1

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#39]
Submit a multi-request job to map tile generator. System will display initial status.
Hit Jobs tab. System will generate the following error:
DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by pauldaustin** [comment]
Environment specific error with getting a database connection.

**Comment by mraross** [comment]
Please move to Review/QA, not Closed.

**Comment by mraross** [comment]
Verified in prod
