### ISSUE TITLE
Client Results Page throws a 500 error

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/cpf#47]
User report

>To get back the result summary, we used to query:
> jobs/<job_number>/results.json
> There does not seem to be any equivalent now…
> We need to “assume” that the results are in:
> jobs/<job_number>/0                    - If there is an error
> jobs/<job_number>/results/1       - If successful

It was actually throwing a 500 error

**Comment by pauldaustin** [comment]
The code to get the list of results in the REST API was trying to query old columns that no longer exist in the data model. Fixed for the next release.

Test by adding /results.json to the end or the job url in the client app. The result should be something like this.

```json
{
  "resourceUri":"http:/localhost/pub/cpf/ws/jobs/1/results.json",
  "title":"Batch Job 1 results",
  "resources":[
    {
      "resourceUri":"http://localhost/pub/cpf/ws/jobs/1/results/1.json",
      "title":"Batch Job 1 result 1",
      "batchJobResultType":"structuredResultData",
      "batchJobResultContentType":"application/vnd.google-earth.kml+xml",
      "expiryDate":"2016-11-24"
    }
  ]
}
```

**Comment by mraross** [comment]
Verified in prod
