### ISSUE TITLE
application/x-geo+json mime type

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/cpf#48]
application/vnd.geo+json is the correct mime type. The GeoJSON library supports both but the list of allowed values in CPF used only the first mime type.

Updated the code that generates the list of input and result mime types to use both. That will show up on the consumer side in the Overview tab for the app.

**NOTE:** The drop down will only contain the official one as it is primarily the description of the type and there is no point having that twice.

**Comment by mraross** [comment]
Very accomodating.
