### ISSUE TITLE
Mandelbrot module is cool

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#5]
Mandelbrot makes testing more fun.
![image](https://cloud.githubusercontent.com/assets/11318574/17453483/3fde8736-5b31-11e6-9d13-093dc5ccfd02.png)

**Comment by pauldaustin** [comment]
No boring testing here

**Comment by mraross** [comment]
Using zenhub extension for chrome to manage github issues.

**Comment by pauldaustin** [comment]
When replying to an email it looks like it includes the original reply text. Probably a good idea just to include the new text and delete the old so that there is less text in the issues when reading it
