### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/cpf#50]
The CPF submit single or multiple request code did not explicitly set the default parameters for fields in the request. This was not an issue on the form as the fields were populated with the default values. However if using the REST API or if the value was deleted from the form then the default value may not get set correctly on the plugin.

Changed the instant and single processing to add the default value for empty job and request parameters and  multiple processing to add the default value for empty job parameters

**Comment by mraross** [comment]
Verified in prod
