### ISSUE TITLE
in delivery, kml output is malformed

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#52]
The final Document tag doesn't have a backslash in it in every KML result file generated. 
```xml
<Document>
```

Tested with a single address in Create single request job and Create multiple request job.

**Comment by pauldaustin** [comment]
Michael,

That error description makes no sense. "There is a tag instead of a tag"?????

Can you provide a sample file and some XML examples of what you mean?

**Comment by mraross** [comment]
It’s the darned marked down. What it literally says is there is a <Document> tag instead of a </Document> tag at the end of the every kml file.

**Comment by pauldaustin** [comment]
Modified the writer to use `</Document>`

**Comment by mraross** [comment]
Verified
