### ISSUE TITLE
where is the REST api doc?

### ISSUE THREAD

**Issue by ll911** [bcgov/cpf#58]
can't find the REST api doc, ps, following reference URL also broken.
http://bcgov.github.io/cpf/java-api

**Comment by pauldaustin** [comment]
Main docs site - http://bcgov.github.io/cpf/

From there the following are accessible.

Client Developer Docs - https://bcgov.github.io/cpf/client.html

REST API https://bcgov.github.io/cpf/cpf-api-app/rest-api/
