### ISSUE TITLE
Get bad gateway error when uploading address list for multi-request job

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#6]
Bad Gateway - The proxy server received an invalid response from an upstream server.
Attached file is actually a CSV file

[geocode_Victoria.txt](https://github.com/bcgov/cpf/files/405167/geocode_Victoria.txt)

**Comment by pauldaustin** [comment]
Works for me. Bad gateway is often a temporary error in the reverse proxy.

**Comment by mraross** [comment]
verified
