### ISSUE TITLE
Can't download a job created in CPF.bgeo.submit single job

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#73]
1. In CPF, batch geocoder, submit single job, I submitted a single address (1175 Douglas). The system created  job 53563, processed it and allowed me to download it from:
https://apps.gov.bc.ca/pub/cpf/secure/ws/jobs/53563/

2. I hit the download icon and got the following message:

This site can’t be reached The webpage at https://apps.gov.bc.ca/pub/cpf/secure/ws/jobs/53563/results/1/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE 

The page url is:
https://apps.gov.bc.ca/pub/cpf/secure/ws/jobs/53563/results/1/

3. I can successfully download the job from the cpf admin app however.

**Comment by BK01** [comment]
Verified as resolved in CPF 5.1.3
