### ISSUE TITLE
failed request file not listed in job results page

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#8]
in Batch job 4694, according to the job information page (at https://delivery.apps.gov.bc.ca/pub/cpf/secure/ws/jobs/4694/#batchJob_clientView ), there were failed requests but the Results page doesn't list a failed requests file.

**Comment by pauldaustin** [comment]
Errors in pre-processing did not create an error file for those records. This has now been fixed

**Comment by mraross** [comment]
verified

**Comment by mraross** [comment]
Verified in prod
