### ISSUE TITLE
Error handling - Empty file input

### ISSUE THREAD

**Issue by BK01** [bcgov/cpf#89]
The following two scenarios were run with CPF 6.1.0. In both cases the jobs remained in the 'submitted' state.

Enhance error handling to account for these cases.

Scenario 1: Submit a CSV file with headings but no content. In this test, the yourId and addressString headings were included.

Scenario 2: Submit a CSV file with no headings or content

**Comment by pauldaustin** [comment]
I just checked and this issue was also in 5.1.3

**Comment by BK01** [comment]
That's right. This issue was created as a result of a new test case introduced for UAT of CPF 6.1.0.

**Comment by pauldaustin** [comment]
Fixed the error handling that was supposed to create an error file in this case

**Comment by BK01** [comment]
Verified in DLV with CPF 6.1.1
