### ISSUE TITLE
CSV file output: Line breaks

### ISSUE THREAD

**Issue by BK01** [bcgov/cpf#90]
Update the CSV output file to use CR-LF line-breaks instead of LF line-breaks.

RFC 4180: https://tools.ietf.org/html/rfc4180

**Comment by mraross** [comment]
Is this a showstopper? In other words, does CPF csv output fail to load into a particular tool (e.g., MS EXCEL), QGIS?

**Comment by BK01** [comment]
Not a showstopper. No errors, this is just an item for the future to match RFC 4180
