### ISSUE TITLE
In geojson output, request for output coordinates in srs 3005 resulted in coordinates in srs 4326

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#94]
Elections BC specifies srs 3005 for their geojson output. Online geocoder supports 3005 correctly.

**Comment by pauldaustin** [comment]
@mraross GeoJSON spec doesn't support anything other than 4326. See https://github.com/bcgov/api-specs/issues/386 for the change requested.

**Comment by pauldaustin** [comment]
Added support to allow non-standard output in different coordinate systems, including the non-standard coordinate system definition in the output

**Comment by BK01** [comment]
Verified in DLV with CPF 6.1.1
